# CSU Machine Learning Assessment 1 - Software Install
A basic template to observe the learning behaviour of algorithms sample by sample.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Establish access to local filesystem

In [ ]:
#Colab requires a mount point to access Google Drive files.

from google.colab import drive
drive.mount('/content/drive')




Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### Local Environment

In [ ]:
import os
#os.chdir('c:/py/data')
os.chdir('/content/drive/My Drive/Colab Notebooks/data')
print(os.getcwd())

/content/drive/My Drive/Colab Notebooks/data


### Modules

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

# Data

### Data sources

In [ ]:
#df = pd.read_csv('Country-data.txt', header=None, encoding='utf-16', sep='\t')
df = pd.read_csv('iris.data', header=None, encoding='utf-8')
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
#sklearn has a built-in dataset for iris
#from sklearn import datasets
#iris = datasets.load_iris()
df.head()

,sepal_length,sepal_width,petal_length,petal_width,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


### Set X and y

In [ ]:
rows = 100
features = [0, 1, 2, 3]
X = df.iloc[0:rows, features].values
y = df.iloc[0:rows, 4].values


### Split and Randomise
The ratio of training samples to test samples is apportioned here to quickly see the efficacy of the algorithm and to get a measure of generalisation capabilities.

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.9, random_state=1, stratify=y)

X = X_train
y = y_train

### Encode classes
Make sure the classification is interpretable by the algorithm here.

In [ ]:
#unit step function
y = np.where(y == 'Iris-setosa', -1 , 1)

#one-hot encoding
#from sklearn.preprocessing import OneHotEncoder
#encoder = OneHotEncoder()
#y_onehot = encoder.fit_transform(y.reshape(-1, 1)).toarray()

for features, truth in zip(X, y):
    print("features: ", features, "truth: ", truth)

features:  [5.2 3.5 1.5 0.2] truth:  -1
features:  [5.  2.3 3.3 1. ] truth:  1
features:  [5.  3.2 1.2 0.2] truth:  -1
features:  [4.4 3.  1.3 0.2] truth:  -1
features:  [6.1 2.9 4.7 1.4] truth:  1
features:  [5.  3.5 1.3 0.3] truth:  -1
features:  [5.9 3.  4.2 1.5] truth:  1
features:  [5.8 2.7 4.1 1. ] truth:  1
features:  [4.7 3.2 1.3 0.2] truth:  -1
features:  [6.  2.9 4.5 1.5] truth:  1


# Model

### Hyperparams
Special hyperparameters associated with algorithms should be here eg. L1 and L2 regularisation. Evaluating all code blocks from this section onwards will re-establish algorithm behaviour.


In [ ]:
eta = 0.01
n_iter = 10
epochs = 10

### Initial Weights
Some algorithms will respond differently depending on initial weights. I have seperated this part to access seed value and the random number generator parameters.

In [ ]:
rgen = np.random.RandomState(1)
w_ = rgen.normal(loc=0.0, scale=0.01, size=1 + X.shape[1])
print('init weights w_: ' , w_)

init weights w_:  [ 0.01624345 -0.00611756 -0.00528172 -0.01072969  0.00865408]


### Cost
For algorithms that review the dimininution of error rates. Nothing to see here for now.

In [ ]:
cost = 0
cost_ = [0]

## Iterator

### Activation Function

In [ ]:
def activation(X):
        return np.where(X >= 0.0, 1, -1) #step activation
        #return(X) #linear activation


### Net Input

In [ ]:
def net_input(X):
        return np.dot(X, w_[1:]) + w_[0]


### Perceptron
$$
\Delta w_i = \eta (y - \hat{y}) x_i
$$

In [ ]:
def ppn_train(index):

    xi = X[index]
    yi = y[index]


    z = net_input(xi)
    output = activation(z)

    delta = (yi - output)

    w_[0] += eta * delta
    w_[1:] += eta * xi.T.dot(delta)
    print("w_ : ", w_)


### Iteration
TODO: This can associated with n_iter hyperparamameter to run several times <br>
Here we can examine how weights are updated sample by sample.<br>
The learned function $\phi$ is provided as the last line.

In [ ]:
index = 0
for index in range(0, len(X)):
    ppn_train(index)
trained_weights = w_
print(trained_weights)


w_ :  [ 0.01624345 -0.00611756 -0.00528172 -0.01072969  0.00865408]
w_ :  [0.03624345 0.09388244 0.04071828 0.05527031 0.02865408]
w_ :  [ 0.01624345 -0.00611756 -0.02328172  0.03127031  0.02465408]
w_ :  [ 0.01624345 -0.00611756 -0.02328172  0.03127031  0.02465408]
w_ :  [ 0.01624345 -0.00611756 -0.02328172  0.03127031  0.02465408]
w_ :  [ 0.01624345 -0.00611756 -0.02328172  0.03127031  0.02465408]
w_ :  [ 0.01624345 -0.00611756 -0.02328172  0.03127031  0.02465408]
w_ :  [ 0.01624345 -0.00611756 -0.02328172  0.03127031  0.02465408]
w_ :  [ 0.01624345 -0.00611756 -0.02328172  0.03127031  0.02465408]
w_ :  [ 0.01624345 -0.00611756 -0.02328172  0.03127031  0.02465408]
[ 0.01624345 -0.00611756 -0.02328172  0.03127031  0.02465408]


### Test other learning algorithms here
$$
\Delta w_j =
\begin{cases}
    \eta \cdot \text{error} \cdot x_{i,j}, & \text{for } j = 1, 2, \dots, m \\
    \eta \cdot \text{error}, & \text{for } j = 0 \text{ (bias term)}
\end{cases}
$$

In [ ]:
print(y) #[ 1  1 -1  1 -1  1  1  1  1 -1  1 -1  1 -1  1]
y_hat = np.dot(X[index], w_[1:]) + w_[0]
error = y[index] - y_hat
print(X[index], y[index])
print(error)
print(eta)
delt_bias = eta*error
delta_w = eta * X[index].T.dot(error) + eta*error
print(delta_w)

cost = 0.5 * error**2
print(cost)

[-1  1 -1 -1  1 -1  1  1 -1  1]
[6.  2.9 4.5 1.5] 1
0.9102813855551698
0.01
[0.0637197  0.03550097 0.05006548 0.02275703]
0.41430610044411986


# Predict
Here we apply the learned function by consulting the test data portion that was partitioned earlier under the section "Split and Randomise".

In [ ]:
def predict(X):
        #phi = np.dot(X.T, trained_weights[1:]) + trained_weights[0]
        phi = X.T.dot(trained_weights[1:]) + trained_weights[0]
        return activation(phi)

for p, y in zip(X_test, y_test):
        print("stimulus: ", p, "response: ", y, ": ", predict(p))



stimulus:  [4.9 3.1 1.5 0.1] response:  Iris-setosa :  -1
stimulus:  [6.6 2.9 4.6 1.3] response:  Iris-versicolor :  1
stimulus:  [5.3 3.7 1.5 0.2] response:  Iris-setosa :  -1
stimulus:  [5.4 3.9 1.3 0.4] response:  Iris-setosa :  -1
stimulus:  [5.1 3.8 1.9 0.4] response:  Iris-setosa :  -1
stimulus:  [5.  3.3 1.4 0.2] response:  Iris-setosa :  -1
stimulus:  [5.4 3.9 1.7 0.4] response:  Iris-setosa :  -1
stimulus:  [6.8 2.8 4.8 1.4] response:  Iris-versicolor :  1
stimulus:  [5.4 3.  4.5 1.5] response:  Iris-versicolor :  1
stimulus:  [5.1 3.8 1.6 0.2] response:  Iris-setosa :  -1
stimulus:  [5.5 2.6 4.4 1.2] response:  Iris-versicolor :  1
stimulus:  [4.6 3.1 1.5 0.2] response:  Iris-setosa :  -1
stimulus:  [5.4 3.4 1.7 0.2] response:  Iris-setosa :  -1
stimulus:  [5.1 3.5 1.4 0.3] response:  Iris-setosa :  -1
stimulus:  [6.4 3.2 4.5 1.5] response:  Iris-versicolor :  1
stimulus:  [5.2 2.7 3.9 1.4] response:  Iris-versicolor :  1
stimulus:  [5.7 3.8 1.7 0.3] response:  Iris-setosa : 